# Generated by Django 4.1.7 on 2023-02-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0005_alter_feed_contentimg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="contentImg",
            field=models.URLField(),
        ),
    ]
